default: &default

  adapter: postgresql

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  timeout: 5000


development:

  <<: *default

  url: "postgresql://postgres:postgres@localhost:5432/phase-3-sinatra-react-project"


test:

  <<: *default

  url: "postgresql://postgres:postgres@localhost:5432/test_phase-3-sinatra-react-project"


production:

  <<: *default

  url: <%= ENV['DATABASE_URL'] %>